### PR TITLE
SS4 fixes

### PR DESCRIPTION
**Pull request by kinglozzer**
Fixes https://github.com/colymba/silverstripe-restfulapi/issues/98 and https://github.com/colymba/silverstripe-restfulapi/issues/97

### CODE REVIEW

**Comment by geekdenz** [comment]
It would be amazing if this could be merged.

**Comment by davidwieler** [comment]
Merge please. Fixes my error.

**Comment by colymba** [comment]
thanks @kinglozzer and sorry for the slow reaction...

**Comment by geekdenz** [comment]
Thanks @colymba ! Helps us a bunch!

**Pull request merged**
